# tab_bar_min_tabs            1
# tab_bar_edge                bottom
# tab_bar_style               powerline
# tab_powerline_style         slanted
# tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

#ctrl+space ctrl+space


map ctrl+space>r reload_config_file

# # Layout
# map ctrl+space>space next_layout
# map ctrl+space>z toggle_layout stack
# map ctrl+space>\ launch --location=vsplit --cwd=current
# map ctrl+space>' launch --location=hsplit --cwd=current
# map ctrl+space>c launch --type=tab --cwd=current
# map ctrl+space>t new_tab !neighbor
#
# # Movement
# map ctrl+space>h previous_window
# map ctrl+space>l next_window
# map ctrl+space>j neighboring_window down
# map ctrl+space>k neighboring_window up
# map ctrl+space>shift+[ move_window left
# map ctrl+space>shift+] move_window right
#
# map ctrl+space>p previous_tab
# map ctrl+space>n next_tab
# map ctrl+space>shift+, move_tab_backward
# map ctrl+space>shift+. move_tab_forward
#
# map ctrl+space>x close_window
# map ctrl+space>q close_tab
#
# map ctrl+space>1 goto_tab 1
# map ctrl+space>2 goto_tab 2
# map ctrl+space>3 goto_tab 3
