# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf

exec-once = /usr/lib/pam_kwallet_init
exec-once = kwalletd6
